/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlserver;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.DatatypeConverter;

public class SuaAd extends javax.swing.JFrame {

    ConnectDth dbconn = new ConnectDth();
    Connection dbConnection = null;
    DefaultTableModel Model;

    public SuaAd() {
        initComponents();
        setResizable(false);
        setSize(735, 480);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtConfirm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        txtNewPass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        getContentPane().setLayout(null);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jTabbedPane1.addTab("Quản Lý Admin", jScrollPane3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 240, 700, 190);

        txtConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtConfirm);
        txtConfirm.setBounds(140, 140, 280, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Xác nhận:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 140, 90, 30);

        txtPass.setEditable(false);
        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtPass);
        txtPass.setBounds(140, 80, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Mật khẩu:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 80, 80, 30);

        txtUsername.setEditable(false);
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.setMinimumSize(new java.awt.Dimension(10, 25));
        txtUsername.setName(""); // NOI18N
        txtUsername.setPreferredSize(new java.awt.Dimension(10, 25));
        getContentPane().add(txtUsername);
        txtUsername.setBounds(140, 20, 280, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tài khoản:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 110, 30);

        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-exit-30.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat);
        btnThoat.setBounds(490, 160, 110, 39);

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-edit-30.png"))); // NOI18N
        btnLuu.setText("Sửa");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        getContentPane().add(btnLuu);
        btnLuu.setBounds(490, 40, 100, 40);

        txtNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNewPass);
        txtNewPass.setBounds(140, 200, 280, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mật khẩu mới:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlserver/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-6, 0, 730, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        if (jTable2.getSelectedRow() >= 0) {
            txtUsername.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 0) + "");
            txtPass.setText(jTable2.getValueAt(jTable2.getSelectedRow(), 1) + "");
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        LoadData();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        dbConnection = dbconn.getSqlConnection();
        if (txtUsername.getText().equals("") || txtPass.getText().equals("") || txtConfirm.getText().equals("") || txtNewPass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "VUI LÒNG ĐIỀN ĐẦY ĐỦ THÔNG TIN! ", "Message Dialog", JOptionPane.WARNING_MESSAGE);
        } else {

            String user = txtUsername.getText();
            String pass = txtPass.getText();
            String confirm = txtConfirm.getText();
            String New = txtNewPass.getText();
            MessageDigest md, newmd;
            try {
                md = MessageDigest.getInstance("MD5");
                md.update(confirm.getBytes());
                byte[] digest = md.digest();
                String myHash = DatatypeConverter.printHexBinary(digest).toUpperCase();
                if (myHash.equals(pass)) {
                    newmd = MessageDigest.getInstance("MD5");
                    newmd.update(New.getBytes());
                    byte[] digest2 = newmd.digest();
                    String myHash2 = DatatypeConverter.printHexBinary(digest2).toUpperCase();
                    String update = "UPDATE TAIKHOAN SET Password = '" + myHash2 + "' WHERE Username = '" + user + "' ";
                    PreparedStatement pst = dbConnection.prepareStatement(update);
                    int rs = pst.executeUpdate();
                    if (rs != 0) {
                        JOptionPane.showMessageDialog(null, "SỬA THÀNH CÔNG", "Information", JOptionPane.INFORMATION_MESSAGE);
                        clearAllInputField();
                        LoadData();

                    } else {

                        JOptionPane.showMessageDialog(null, "SỬA THẤT BẠI", "Information", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
                else{
                    JOptionPane.showMessageDialog(null, "MẬT KHẨU XÁC THỰC KHÔNG ĐÚNG", "Information", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(SuaAd.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(SuaAd.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnLuuActionPerformed
    private void LoadData() {
        Model = (DefaultTableModel) jTable2.getModel();
        Model.setRowCount(0);
        dbConnection = dbconn.getSqlConnection();
        String qlsv = "SELECT * FROM TAIKHOAN";
        try {
            PreparedStatement pst = dbConnection.prepareStatement(qlsv);
            ResultSet rs = pst.executeQuery();
            jTable2.removeAll();
            String[] arr = {"Tên tài khoản", "Mật khẩu"};
            Model = new DefaultTableModel(arr, 0);
            while (rs.next()) {

                Vector vec = new Vector();
                vec.add(rs.getString("Username"));
                vec.add(rs.getString("Password"));
                Model.addRow(vec);
            }

            jTable2.setModel(Model);
        } catch (SQLException ex) {
            Logger.getLogger(QLData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clearAllInputField() {
        txtUsername.setText("");
        txtPass.setText("");
        txtConfirm.setText("");
        txtNewPass.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaAd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaAd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtConfirm;
    private javax.swing.JTextField txtNewPass;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
